name: Docker Build and Push

on:
  repository_dispatch:
    types: [build-docker-image]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Pugmatt
          repo: BedrockConnect
          excludes: prerelease, draft
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/custom-servers
          file: ./docker/custom-servers/Dockerfile
          push: true
          tags: aspruyt/bedrockconnect:latest, aspruyt/bedrockconnect:${{ steps.version.outputs.release }}
